In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [3]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns = columns)

In [7]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selection and Indexing of Columns**

In [8]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
df2[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**Creating a new column**

In [10]:
df2['Designation'] = ["Doctor","Eng.","Doctor","Eng."]

In [11]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

**Removing Columns**

In [14]:
df2.drop(0, axis=0)

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
2  Peter   29  Berlin   62000      Doctor
3  Linda   42  London   85000        Eng.

In [18]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [17]:
df2 = df2.drop('Designation', axis=1)

**Selecting Rows**

In [19]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
df2.loc[[0,2]]

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

In [25]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

**Selecting Subsets of Rows and Columns**

In [26]:
df.loc[[0,1]][['City', 'Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

**Conditional Selection**

In [27]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
#I only want to see those people whose age is above 30
df2[df2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [30]:
#I only want poeple whose age is above 30 and their city must be paris
df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000